### ISSUE TITLE
object_detection_app.py hangs

### ISSUE THREAD

**Issue by dtaillie** [datitran/object_detector_app#17]
Output looks the same as example until the line:

`[INFO/ForkPoolWorker-2] process shutting down`

Then getting the traceback:

`Traceback (most recent call last):
  File "/home/daniel/anaconda2/envs/object-detection/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/daniel/anaconda2/envs/object-detection/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/daniel/anaconda2/envs/object-detection/lib/python3.5/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "object_detection_app.py", line 79, in worker
    output_q.put(detect_objects(frame, sess, detection_graph))
  File "object_detection_app.py", line 49, in detect_objects
    feed_dict={image_tensor: image_np_expanded})
  File "/home/daniel/anaconda2/envs/object-detection/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/daniel/anaconda2/envs/object-detection/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 968, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/daniel/anaconda2/envs/object-detection/lib/python3.5/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[INFO/ForkPoolWorker-2] process exiting with exitcode 1`

Unsure the cause of the issue. I am using OpenCV 3.1 instead of 3.0 and replaced:

`- menpo::tbb=4.3_20141023=0`

with:

`- menpo::tbb`

although I don't see how they would be related.

Any intuition as to what the issue could be?

Thanks.

Full output:
`(object-detection) daniel@daniel-Satellite-C55Dt-A:~/bin/Object-Detector-App$ python object_detection_app.py --source=0 --num-workers=2
[DEBUG/MainProcess] created semlock with handle 139755691372544
[DEBUG/MainProcess] created semlock with handle 139755691368448
[DEBUG/MainProcess] created semlock with handle 139755691364352
[DEBUG/MainProcess] Queue._after_fork()
[DEBUG/MainProcess] created semlock with handle 139755691360256
[DEBUG/MainProcess] created semlock with handle 139755691356160
[DEBUG/MainProcess] created semlock with handle 139755691352064
[DEBUG/MainProcess] Queue._after_fork()
[DEBUG/MainProcess] created semlock with handle 139755691347968
[DEBUG/MainProcess] created semlock with handle 139755691343872
[DEBUG/MainProcess] created semlock with handle 139755691339776
[DEBUG/MainProcess] created semlock with handle 139755691335680
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-1] Queue._after_fork()
[DEBUG/ForkPoolWorker-1] Queue._after_fork()
[INFO/ForkPoolWorker-1] child process calling self.run()
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[INFO/ForkPoolWorker-2] child process calling self.run()
[DEBUG/MainProcess] Queue._start_thread()
[DEBUG/MainProcess] doing self._thread.start()
[DEBUG/MainProcess] starting thread to feed data to pipe
[DEBUG/MainProcess] ... done self._thread.start()
2017-08-02 16:02:44.171442: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-02 16:02:44.171442: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-02 16:02:44.171513: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-02 16:02:44.171516: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-02 16:02:44.171542: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-02 16:02:44.171554: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
[INFO/ForkPoolWorker-2] process shutting down
[DEBUG/ForkPoolWorker-2] running all "atexit" finalizers with priority >= 0
[DEBUG/ForkPoolWorker-2] running the remaining "atexit" finalizers
Process ForkPoolWorker-2:
Traceback (most recent call last):
  File "/home/daniel/anaconda2/envs/object-detection/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/daniel/anaconda2/envs/object-detection/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/daniel/anaconda2/envs/object-detection/lib/python3.5/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "object_detection_app.py", line 79, in worker
    output_q.put(detect_objects(frame, sess, detection_graph))
  File "object_detection_app.py", line 49, in detect_objects
    feed_dict={image_tensor: image_np_expanded})
  File "/home/daniel/anaconda2/envs/object-detection/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/daniel/anaconda2/envs/object-detection/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 968, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/daniel/anaconda2/envs/object-detection/lib/python3.5/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[INFO/ForkPoolWorker-2] process exiting with exitcode 1
[DEBUG/MainProcess] cleaning up worker 1
[Level 5/MainProcess] finalizer calling <built-in function close> with args (13,) and kwargs {}
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[INFO/ForkPoolWorker-3] child process calling self.run()
2017-08-02 16:02:54.370080: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-02 16:02:54.370152: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-02 16:02:54.370179: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
`

**Comment by datitran** [comment]
Hmm it seems that there is no input at all as you're getting a `NoneType`. Not sure why this happens. I actually have problems with OpenCV 3.1. Can you try it with 3.0? In terms of `tbb`, this shouldn't matter.
