### ISSUE TITLE
int() argument must be a string

### ISSUE THREAD

**Issue by Waffleboy** [datitran/object_detector_app#23]
Followed your installation instructions, and I found this error
```

name: GeForce GTX 1060
major: 6 minor: 1 memoryClockRate (GHz) 1.733
pciBusID 0000:01:00.0
Total memory: 2.94GiB
Free memory: 2.42GiB
2017-08-27 18:48:40.677002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-08-27 18:48:40.677008: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-08-27 18:48:40.677018: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0)
[INFO/ForkPoolWorker-2] process shutting down
[DEBUG/ForkPoolWorker-2] running all "atexit" finalizers with priority >= 0
[DEBUG/ForkPoolWorker-2] running the remaining "atexit" finalizers
Process ForkPoolWorker-2:
Traceback (most recent call last):
  File "/storage/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/storage/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/storage/anaconda3/lib/python3.6/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "object_detection_app.py", line 83, in worker
    output_q.put(detect_objects(frame, sess, detection_graph))
  File "object_detection_app.py", line 49, in detect_objects
    feed_dict={image_tensor: image_np_expanded})
  File "/storage/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/storage/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1093, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/storage/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

This is really weird, I cant seem to find out why this is happening. Tensorflow is installed correctly, my libraries are all upgraded and I have protobuf. 

Would you happen to have any idea? :)

**Comment by datitran** [comment]
As you can see there is a NoneType and it expects something else. Is your webcam really streaming? Maybe you can set up some breakpoints and see what the debugger says...

**Comment by Waffleboy** [comment]
No, the webcam light doesn't turn on. I tried on another laptop and the webcam light turns on. Strange because they're both running Ubuntu 16. Do you have any clue as to where I should look at?

**Comment by datitran** [comment]
Well it's probably some OpenCV error or the source for the camera is not correctly defined...

**Comment by Waffleboy** [comment]
Thank you for that!! You're right, `opencv-python` the package for opencv from the repository has issues and doesn't support video. Changing it to `conda install -c menpo opencv3` worked!

**Comment by TranVanLy107** [comment]
Hi datitran,
i'm runing live stream video camera using RTSP protocol , it can run about 1 minute and than have a proplem that:
Traceback (most recent call last):
File "Vehicle_classifier_counting.py", line 198, in 
feed_dict={image_tensor: frame_expanded})
File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
run_metadata_ptr)
File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run
np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Can you help me, please!

**Comment by dvjayk13** [comment]
> Hi datitran,
> i'm runing live stream video camera using RTSP protocol , it can run about 1 minute and than have a proplem that:
> Traceback (most recent call last):
> File "Vehicle_classifier_counting.py", line 198, in
> feed_dict={image_tensor: frame_expanded})
> File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
> run_metadata_ptr)
> File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run
> np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
> File "C:\ProgramData\Anaconda3\envs\tensorflow1\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
> return array(a, dtype, copy=False, order=order)
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> 
> Can you help me, please!

I'm facing the same issue with rtsp stream. Its working properly for webcam
Did you found any solution?
