### ISSUE TITLE
Image unsupported by OpenCV

### ISSUE THREAD

**Issue by Dremet** [datitran/object_detector_app#3]
Hi!

So, first, I tried to copy your environment:
```
conda env create -f environment.yml
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .............


NoPackagesFoundError: Package missing in current linux-64 channels: 
  - tbb 4.3_20141023 0 
```

After that did not work, I tried to set it up on my own. 

```
conda list
# packages in environment at /home/dremet/anaconda3/envs/object_recog:
#
freetype                  2.5.5                         2  
funcsigs                  0.4                      py35_0  
hdf5                      1.8.17                        1  
jbig                      2.1                           0  
jpeg                      8d                            2  
lcms                      1.19                          0  
libpng                    1.6.27                        0  
libprotobuf               3.2.0                         0  
libtiff                   4.0.6                         2  
mkl                       2017.0.1                      0  
mock                      2.0.0                    py35_0  
numpy                     1.12.1                   py35_0  
opencv                    3.1.0               np112py35_1  
openssl                   1.0.2l                        0  
pbr                       1.10.0                   py35_0  
pillow                    3.4.2                    py35_0  
pip                       9.0.1                    py35_1  
protobuf                  3.2.0                    py35_0  
python                    3.5.3                         1  
readline                  6.2                           2  
setuptools                27.2.0                   py35_0  
six                       1.10.0                   py35_0  
sqlite                    3.13.0                        0  
tensorflow                1.1.0               np112py35_0  
tk                        8.5.18                        0  
werkzeug                  0.12.2                   py35_0  
wheel                     0.29.0                   py35_0  
xz                        5.2.2                         1  
zlib                      1.2.8                         3 
```

Now, when I run the script, I get this output (until I interrupted with my keyboard):
```
python object_detection_app.py --source=0
[DEBUG/MainProcess] created semlock with handle 140384818184192
[DEBUG/MainProcess] created semlock with handle 140384818180096
[DEBUG/MainProcess] created semlock with handle 140384818176000
[DEBUG/MainProcess] Queue._after_fork()
[DEBUG/MainProcess] created semlock with handle 140384818171904
[DEBUG/MainProcess] created semlock with handle 140384818167808
[DEBUG/MainProcess] created semlock with handle 140384818163712
[DEBUG/MainProcess] Queue._after_fork()
[DEBUG/MainProcess] created semlock with handle 140384818159616
[DEBUG/MainProcess] created semlock with handle 140384818155520
[DEBUG/MainProcess] created semlock with handle 140384818151424
[DEBUG/MainProcess] created semlock with handle 140384818147328
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[INFO/ForkPoolWorker-2] child process calling self.run()
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
Unable to stop the stream: Device or resource busy
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[INFO/ForkPoolWorker-3] child process calling self.run()
[DEBUG/MainProcess] Queue._start_thread()
[DEBUG/MainProcess] doing self._thread.start()
[DEBUG/MainProcess] starting thread to feed data to pipe
[DEBUG/MainProcess] ... done self._thread.start()
2017-06-26 09:50:05.562006: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-26 09:50:05.562039: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-26 09:50:05.562045: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
[INFO/ForkPoolWorker-3] process shutting down
[DEBUG/ForkPoolWorker-3] running all "atexit" finalizers with priority >= 0
[DEBUG/ForkPoolWorker-3] running the remaining "atexit" finalizers
Process ForkPoolWorker-3:
Traceback (most recent call last):
  File "/home/dremet/anaconda3/envs/object_recog/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/dremet/anaconda3/envs/object_recog/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dremet/anaconda3/envs/object_recog/lib/python3.5/multiprocessing/pool.py", line 103, in worker
    initializer(*initargs)
  File "object_detection_app.py", line 79, in worker
    output_q.put(detect_objects(frame, sess, detection_graph))
  File "object_detection_app.py", line 49, in detect_objects
    feed_dict={image_tensor: image_np_expanded})
  File "/home/dremet/anaconda3/envs/object_recog/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/dremet/anaconda3/envs/object_recog/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 954, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/dremet/anaconda3/envs/object_recog/lib/python3.5/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[INFO/ForkPoolWorker-3] process exiting with exitcode 1
[DEBUG/MainProcess] cleaning up worker 1
[Level 5/MainProcess] finalizer calling <built-in function close> with args (13,) and kwargs {}
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-4] Queue._after_fork()
[DEBUG/ForkPoolWorker-4] Queue._after_fork()
[INFO/ForkPoolWorker-4] child process calling self.run()
2017-06-26 09:50:05.625579: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-26 09:50:05.625605: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-26 09:50:05.625613: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-26 09:50:14.247294: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-26 09:50:14.247325: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-26 09:50:14.247332: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.

```
Help is very appreciated.

**Comment by ghost** [comment]
`tensorflow                1.1.0               np112py35_0  
`

Make sure you use Tensorflow 1.2.0

**Comment by Dremet** [comment]
That did change sth. although it's still not working. 

```
python3 object_detection_app.py 
[DEBUG/MainProcess] created semlock with handle 140303170584576
[DEBUG/MainProcess] created semlock with handle 140303170580480
[DEBUG/MainProcess] created semlock with handle 140303170576384
[DEBUG/MainProcess] Queue._after_fork()
[DEBUG/MainProcess] created semlock with handle 140303170572288
[DEBUG/MainProcess] created semlock with handle 140303170568192
[DEBUG/MainProcess] created semlock with handle 140303170564096
[DEBUG/MainProcess] Queue._after_fork()
[DEBUG/MainProcess] created semlock with handle 140303170560000
[DEBUG/MainProcess] created semlock with handle 140303170555904
[DEBUG/MainProcess] created semlock with handle 140303170551808
[DEBUG/MainProcess] created semlock with handle 140303170547712
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[DEBUG/ForkPoolWorker-2] Queue._after_fork()
[INFO/ForkPoolWorker-2] child process calling self.run()
[DEBUG/MainProcess] added worker
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[DEBUG/ForkPoolWorker-3] Queue._after_fork()
[INFO/ForkPoolWorker-3] child process calling self.run()
Corrupt JPEG data: 1 extraneous bytes before marker 0xd0
[DEBUG/MainProcess] Queue._start_thread()
[DEBUG/MainProcess] doing self._thread.start()
[DEBUG/MainProcess] starting thread to feed data to pipe
[DEBUG/MainProcess] ... done self._thread.start()
Corrupt JPEG data: 1 extraneous bytes before marker 0xd2
Corrupt JPEG data: 1 extraneous bytes before marker 0xd3
Corrupt JPEG data: 2 extraneous bytes before marker 0xd5
Corrupt JPEG data: 2 extraneous bytes before marker 0xd6
Corrupt JPEG data: 1 extraneous bytes before marker 0xd4
Corrupt JPEG data: 1 extraneous bytes before marker 0xd5
Corrupt JPEG data: 1 extraneous bytes before marker 0xd3
Corrupt JPEG data: 1 extraneous bytes before marker 0xd3
Corrupt JPEG data: 1 extraneous bytes before marker 0xd4
Corrupt JPEG data: 1 extraneous bytes before marker 0xd1
Corrupt JPEG data: 1 extraneous bytes before marker 0xd2
Corrupt JPEG data: 1 extraneous bytes before marker 0xd4
Corrupt JPEG data: 2 extraneous bytes before marker 0xd0
Corrupt JPEG data: 5 extraneous bytes before marker 0xd7
…
```

```
Corrupt JPEG data: 1 extraneous bytes before marker 0xd5
Corrupt JPEG data: 1 extraneous bytes before marker 0xd7
Corrupt JPEG data: 2 extraneous bytes before marker 0xd7
Corrupt JPEG data: 1 extraneous bytes before marker 0xd1
Corrupt JPEG data: 1 extraneous bytes before marker 0xd1
2017-06-27 18:14:13.799156: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-27 18:14:13.799188: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-27 18:14:13.799194: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Corrupt JPEG data: 1 extraneous bytes before marker 0xd0
Corrupt JPEG data: 1 extraneous bytes before marker 0xd1
2017-06-27 18:14:13.846609: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-27 18:14:13.846635: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-27 18:14:13.846641: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Corrupt JPEG data: 2 extraneous bytes before marker 0xd0
Corrupt JPEG data: 3 extraneous bytes before marker 0xd0
Corrupt JPEG data: 2 extraneous bytes before marker 0xd1
Corrupt JPEG data: 1 extraneous bytes before marker 0xd6
Corrupt JPEG data: 4 extraneous bytes before marker 0xd3
Corrupt JPEG data: 2 extraneous bytes before marker 0xd2
…
```


```
Corrupt JPEG data: 1 extraneous bytes before marker 0xd1
Corrupt JPEG data: 4 extraneous bytes before marker 0xd3
Corrupt JPEG data: 1 extraneous bytes before marker 0xd0
Corrupt JPEG data: 1 extraneous bytes before marker 0xd0
Corrupt JPEG data: 2 extraneous bytes before marker 0xd7
[DEBUG/ForkPoolWorker-3] Queue._start_thread()
[DEBUG/ForkPoolWorker-3] doing self._thread.start()
[DEBUG/ForkPoolWorker-3] starting thread to feed data to pipe
[DEBUG/ForkPoolWorker-3] ... done self._thread.start()
OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /opt/conda/conda-bld/opencv_1491943704081/work/opencv-3.1.0/modules/highgui/src/window.cpp, line 545
Traceback (most recent call last):
  File "object_detection_app.py", line 120, in <module>
    cv2.imshow('Video', output_q.get())
cv2.error: /opt/conda/conda-bld/opencv_1491943704081/work/opencv-3.1.0/modules/highgui/src/window.cpp:545: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage

Corrupt JPEG data: 1 extraneous bytes before marker 0xd2
Corrupt JPEG data: 1 extraneous bytes before marker 0xd3
Corrupt JPEG data: 1 extraneous bytes before marker 0xd3
Corrupt JPEG data: 3 extraneous bytes before marker 0xd7
Corrupt JPEG data: 3 extraneous bytes before marker 0xd2
Corrupt JPEG data: 1 extraneous bytes before marker 0xd1
Corrupt JPEG data: 1 extraneous bytes before marker 0xd4
Corrupt JPEG data: 5 extraneous bytes before marker 0xd1
Corrupt JPEG data: 1 extraneous bytes before marker 0xd6
Corrupt JPEG data: 1 extraneous bytes before marker 0xd4

```


So I did read "install libgtk2.0-dev and pkg-config" and I also did this. I then reinstalled opencv using anaconda, but that does not change anything.

**Comment by luiscosio** [comment]
Same issue trying to run it on Ubuntu 17.04.

I think TPP should be  https://anaconda.org/conda-forge/tbb for Linux.

But still, getting same error as you:

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by datitran** [comment]
@Dremet Seems to be an OpenCV problem. On Stackoverflow I found this [thread](https://stackoverflow.com/questions/15533338/opencv-error-on-ubuntu-webcam-logitech-c270-capture-highgui-error-v4l-v4l2).

Also in the error it says: 
`OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /opt/conda/conda-bld/opencv_1491943704081/work/opencv-3.1.0/modules/highgui/src/window.cpp, line 545`

I think you need to re-compile it from the build.

@luiscosio TBB shouldn't be the problem. You get this error if you don't use Tensorflow 1.2.
