### ISSUE TITLE
No checkpoint found:

### ISSUE THREAD

**Issue by Radhesh2711** [datitran/object_detector_app#56]
Traceback (most recent call last):
  File "demo.py", line 128, in <module>
    main(args)
  File "demo.py", line 97, in main
    checkpoint = load_checkpoint(args.resume)
  File "C:\Users\Radhesh Harlalka\Desktop\Scene_text_PRL\aster.pytorch-master\lib\utils\serialization.py", line 66, in load_checkpoint
    raise ValueError("=> No checkpoint found at '{}'".format(load_path))
ValueError: => No checkpoint found at 'C:/Program Files/Git/data/mkyang/logs/recognition/aster.pytorch/logs/baseline_aster/baseline_aster/demo.pth.tar'

**Comment by Radhesh2711** [comment]
I cant understand why am I facing this issue as I have already specified the --resume argument of main_test_image.sh to the path of demo.pth.tar file. Still, this issue persists. Can anyone help?
